"""
parse_vcs.py — VCS Gate-Level Simulation & PrimeTime PX report parser (Path 3).

Extracts:
  execution_cycles  : int    (cycle-accurate count from VCS simulation log)
  hw_accuracy       : float  (hardware-measured accuracy, 0.0 ~ 1.0)
  dynamic_power_mw  : float  (mW, from PtPX power report using SAIF activity)
  leakage_power_mw  : float  (mW)

Expected files in `reports_dir/`:
  vcs_simulation.log   — VCS stdout captured by Makefile (contains $display output)
  ptpx_power.rpt       — PrimeTime PX power report

Testbench $display conventions (matched by the regex patterns below):
  $display("Total cycles: %0d", cycle_count);
  $display("HW Accuracy: %0d / %0d", correct_count, `TB_NUM_VECTORS);

If the testbench uses a different $display format, update the regex patterns
in _parse_vcs_log() accordingly.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict

from .parse_dc import _scale_power


# ── VCS Simulation Log Parser ─────────────────────────────────────────────────

def _parse_vcs_log(log_text: str) -> Dict[str, Any]:
    """
    Extract cycle count and hardware accuracy from the VCS simulation log.

    Matches the $display statements in tb_top.sv:
      "Total cycles: <N>"
      "HW Accuracy: <correct> / <total>"

    Returns:
        {
          "execution_cycles": int,
          "hw_correct":       int,   # number of correctly classified vectors
          "hw_total":         int,   # total number of test vectors
          "hw_accuracy":      float, # hw_correct / hw_total
        }
    """
    # ── Cycle Count ──────────────────────────────────────────────────────────
    # Matches: "Total cycles: 12345" (generated by tb_top.sv $display)
    cycle_patterns = [
        re.compile(r"Total cycles:\s+([0-9]+)", re.IGNORECASE),
        re.compile(r"SIM_CYCLES:\s*([0-9]+)", re.IGNORECASE),
        re.compile(r"Execution cycles:\s+([0-9]+)", re.IGNORECASE),
    ]
    cycles: int | None = None
    for pat in cycle_patterns:
        m = pat.search(log_text)
        if m:
            cycles = int(m.group(1))
            break

    if cycles is None:
        raise ValueError(
            "Could not find cycle count in VCS simulation log.\n"
            "Expected format: 'Total cycles: <N>'\n"
            "Check that tb_top.sv contains: "
            '$display("Total cycles: %0d", cycle_count);'
        )

    # ── Hardware Accuracy ─────────────────────────────────────────────────────
    # Matches: "HW Accuracy: 47 / 50" (generated by tb_top.sv $display)
    acc_pattern = re.compile(
        r"HW Accuracy:\s+([0-9]+)\s*/\s*([0-9]+)", re.IGNORECASE
    )
    acc_match = acc_pattern.search(log_text)

    if acc_match:
        hw_correct = int(acc_match.group(1))
        hw_total   = int(acc_match.group(2))
        hw_accuracy = hw_correct / hw_total if hw_total > 0 else 0.0
    else:
        # Accuracy line is optional; default to -1 to signal "not captured"
        hw_correct  = -1
        hw_total    = -1
        hw_accuracy = -1.0

    return {
        "execution_cycles": cycles,
        "hw_correct":       hw_correct,
        "hw_total":         hw_total,
        "hw_accuracy":      hw_accuracy,
    }


# ── PrimeTime PX Power Report Parser ─────────────────────────────────────────

def _parse_ptpx_power(report_text: str) -> Dict[str, float]:
    """
    Extract dynamic and leakage power from PrimeTime PX report.
    Uses the same regex as parse_dc._parse_power (PtPX format is identical).

    Example lines:
      Total Dynamic Power    =    10.5423 mW
      Cell Leakage Power     =   324.1234 uW
    """
    dynamic_pattern = re.compile(
        r"Total Dynamic Power\s+=\s+([0-9.]+)\s+(\w+)", re.IGNORECASE
    )
    leakage_pattern = re.compile(
        r"Cell Leakage Power\s+=\s+([0-9.]+)\s+(\w+)", re.IGNORECASE
    )

    dynamic_match = dynamic_pattern.search(report_text)
    leakage_match = leakage_pattern.search(report_text)

    if not dynamic_match:
        raise ValueError(
            "Could not find 'Total Dynamic Power' in PtPX report.\n"
            "Check that pt_shell ran successfully and ptpx_power.rpt is valid."
        )

    dynamic_mw = _scale_power(float(dynamic_match.group(1)), dynamic_match.group(2))
    leakage_mw = (
        _scale_power(float(leakage_match.group(1)), leakage_match.group(2))
        if leakage_match
        else 0.0
    )

    return {
        "dynamic_power_mw": dynamic_mw,
        "leakage_power_mw": leakage_mw,
    }


# ── Public API ────────────────────────────────────────────────────────────────

def parse_vcs_reports(reports_dir: str) -> Dict[str, Any]:
    """
    Parse VCS simulation log and PtPX power report to obtain cycle-accurate
    execution statistics and gate-level dynamic power.

    Returns:
        {
          "execution_cycles":  int,
          "hw_accuracy":       float,  # 0.0 ~ 1.0, or -1.0 if not captured
          "dynamic_power_mw":  float,  # mW (from PtPX with SAIF activity)
          "leakage_power_mw":  float,  # mW
        }

    Raises:
        FileNotFoundError: if a required report file is missing.
        ValueError:        if a required field cannot be extracted.
    """
    reports_path = Path(reports_dir)
    vcs_log  = reports_path / "vcs_simulation.log"
    ptpx_rpt = reports_path / "ptpx_power.rpt"

    for f in [vcs_log, ptpx_rpt]:
        if not f.exists():
            raise FileNotFoundError(
                f"Expected report not found: {f}\n"
                "Ensure 'make sim' and 'make power' completed successfully."
            )

    sim_metrics   = _parse_vcs_log(vcs_log.read_text(encoding="utf-8", errors="replace"))
    power_metrics = _parse_ptpx_power(ptpx_rpt.read_text(encoding="utf-8", errors="replace"))

    return {
        "execution_cycles":  sim_metrics["execution_cycles"],
        "hw_accuracy":       sim_metrics["hw_accuracy"],
        **power_metrics,
    }
