// =============================================================================
// tb_top.sv — Parameterized Gate-Level Simulation Testbench
//
// AUTO-PARAMETERIZED via:
//   - config_macros.svh  : Hardware geometry (HV_LENGTH, INPUTS_NUM, etc.)
//   - tb_macros.svh      : Test environment (clock period, number of vectors)
//
// Test Data (loaded via $readmemh from the data/ directory):
//   inputs.hex   : Input feature vectors, one per line, hex-encoded
//   labels.hex   : Golden label per input vector
//   weights.hex  : HDnn class hypervectors (for RRAM initialisation)
//
// Outputs written to reports/:
//   vcs_simulation.log  : Contains "Total cycles: N" and "HW Accuracy: A / B"
//   activity.saif       : Switching activity for PrimeTime PX power analysis
//
// IMPORTANT: Instantiate the correct top-level DUT module below.
//            Replace `hdnn_top` with the actual synthesized top module name.
// =============================================================================

`timescale 1ns / 1ps

`include "../include/config_macros.svh"
`include "tb_macros.svh"

module tb_top;

// ── Clock & Reset ─────────────────────────────────────────────────────────────
reg clk;
reg rst_n;

// Generate clock with period from tb_macros.svh (unit: ns)
initial clk = 0;
always #(`TB_CLK_PERIOD_NS / 2.0) clk = ~clk;

// ── DUT Port Signals ──────────────────────────────────────────────────────────
// Adapt the following port declarations to match your actual RTL top-level.
// The widths should be driven by macros from config_macros.svh.

reg  [`HV_LENGTH-1:0]      dut_hv_in;       // Input hypervector
reg  [`ENC_INPUTS_NUM-1:0] dut_feature_in;  // Encoded feature input
reg                         dut_valid_in;    // Input valid strobe
wire [`HV_LENGTH-1:0]      dut_hv_out;      // Output (class match) hypervector
wire                         dut_valid_out;  // Output valid strobe
wire [7:0]                   dut_pred_class; // Predicted class label (8-bit)

// ── DUT Instantiation ─────────────────────────────────────────────────────────
// Replace 'hdnn_top' with your actual synthesized module name.
hdnn_top u_dut (
    .clk        (clk),
    .rst_n      (rst_n),
    .feature_in (dut_feature_in),
    .valid_in   (dut_valid_in),
    .pred_class (dut_pred_class),
    .valid_out  (dut_valid_out)
);

// ── Test Vector Memory ────────────────────────────────────────────────────────
// Storage for test vectors loaded from HEX files
reg [7:0] input_mem  [`TB_NUM_VECTORS-1:0][`ENC_INPUTS_NUM-1:0]; // input features
reg [7:0] label_mem  [`TB_NUM_VECTORS-1:0];                       // golden labels
reg [7:0] weight_mem [`HV_LENGTH-1:0][`HV_LENGTH-1:0];           // class HVs (RRAM init)

// ── Cycle Counter & Accuracy ──────────────────────────────────────────────────
integer cycle_count;
integer correct_count;
integer i;

// ── SAIF Activity Dump Setup ──────────────────────────────────────────────────
// PrimeTime PX reads this file to calculate exact dynamic power.
initial begin
    $set_gate_level_monitoring("rtl_on");
    $set_toggle_region(u_dut);
    $toggle_start();
end

// ── Main Test Sequence ────────────────────────────────────────────────────────
initial begin
    // Load test data from hex files (generated by path1_software.dump_hex_data)
    $readmemh(`TB_INPUT_FILE,  input_mem);
    $readmemh(`TB_GOLDEN_FILE, label_mem);
    $readmemh(`TB_WEIGHT_FILE, weight_mem);

    // Initialise counters
    cycle_count   = 0;
    correct_count = 0;

    // Reset DUT
    rst_n        = 0;
    dut_valid_in = 0;
    dut_feature_in = 0;
    repeat(4) @(posedge clk);
    rst_n = 1;
    @(posedge clk);

    // Drive each test vector through the DUT
    for (i = 0; i < `TB_NUM_VECTORS; i = i + 1) begin
        // Present input feature vector
        dut_feature_in = input_mem[i];
        dut_valid_in   = 1;
        @(posedge clk);
        cycle_count = cycle_count + 1;

        // Wait for DUT output valid signal
        dut_valid_in = 0;
        while (!dut_valid_out) begin
            @(posedge clk);
            cycle_count = cycle_count + 1;
        end

        // Check prediction against golden label
        if (dut_pred_class == label_mem[i]) begin
            correct_count = correct_count + 1;
        end

        // Allow one idle cycle between vectors
        @(posedge clk);
        cycle_count = cycle_count + 1;
    end

    // ── Stop Activity Monitoring & Dump SAIF ──────────────────────────────
    $toggle_stop();
    $toggle_report("reports/activity.saif", 1.0e-9, "tb_top");

    // ── Print Results (parsed by parse_vcs.py) ────────────────────────────
    $display("Total cycles: %0d", cycle_count);
    $display("HW Accuracy: %0d / %0d", correct_count, `TB_NUM_VECTORS);

    $finish;
end

// ── Watchdog Timer ────────────────────────────────────────────────────────────
// Abort simulation if it runs too long (safety net against DUT hangs).
// 10 million cycles @ TB_CLK_PERIOD_NS is typically well over 10 ms at 100 MHz.
initial begin
    #(10_000_000 * `TB_CLK_PERIOD_NS);
    $display("[WATCHDOG] Simulation exceeded time limit. Aborting.");
    $finish;
end

// ── VCD Dump (optional, for waveform debug) ───────────────────────────────────
// Uncomment for waveform capture. Disable in production runs to save disk space.
// initial begin
//     $dumpfile("reports/wave.vcd");
//     $dumpvars(0, tb_top);
// end

endmodule
