// AUTO-GENERATED by json_to_svh.py — DO NOT EDIT MANUALLY
// Used by LFSR-based testbenches (tb_core_timing.sv / tb_hd_top_timing.sv).
// No hex data files are required — testbench generates its own LFSR stimuli.
`ifndef TB_MACROS_SVH
`define TB_MACROS_SVH

`define TB_CLK_PERIOD_NS  10.0

`endif // TB_MACROS_SVH
