"""
json_to_svh.py — Server-side parameter translation script.

Reads a JSON parameter dictionary (from stdin or function call) and:
  1. Applies the software-to-RTL mathematical mapping defined in README Section 2.2.
  2. Writes `hardware/include/config_macros.svh` with `define macros.
  3. Patches `hardware/dc/synth.tcl` to inject the correct `create_clock` period
     derived from the `frequency` parameter.

Usage (called by eda_server.py via subprocess):
  echo '<json_params>' | python json_to_svh.py

The JSON is read from stdin. Exit code 0 = success, non-zero = failure.
"""

from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

# ── File paths (relative to this script's location on the EDA server) ──────
SCRIPT_DIR = Path(__file__).parent
HARDWARE_DIR = SCRIPT_DIR / "hardware"
SVH_OUTPUT = HARDWARE_DIR / "include" / "config_macros.svh"
TCL_TEMPLATE = HARDWARE_DIR / "dc" / "synth_template.tcl"
TCL_OUTPUT = HARDWARE_DIR / "dc" / "synth.tcl"


# ── Mathematical Mapping ─────────────────────────────────────────────────────

def _derive_macros(params: dict) -> dict[str, int | str]:
    """
    Apply the mathematical relationships from README Section 2.2 to produce
    a flat dictionary of {MACRO_NAME: value} entries for the SVH file.

    Parameter conventions (all integers unless noted):
      hd_dim          : Hypervector dimension
      inner_dim       : Inner dimension of the HD encoder
      reram_size      : Number of RRAM rows (must be power-of-2 friendly)
      cnn_x_dim_1/2  : CNN spatial PE columns (Layer 1/2)
      cnn_y_dim_1/2  : CNN spatial PE rows (Layer 1/2)
      out_channels_1/2: CNN output channel count (Layer 1/2)
      encoder_x_dim   : Encoder PE columns
      encoder_y_dim   : Encoder PE rows
      frequency       : Operating frequency in Hz (e.g. 1e8 = 100 MHz)
    """
    hd_dim: int = int(params["hd_dim"])
    inner_dim: int = int(params["inner_dim"])
    reram_size: int = int(params["reram_size"])

    cnn_x_dim_1: int = int(params["cnn_x_dim_1"])
    cnn_y_dim_1: int = int(params["cnn_y_dim_1"])
    cnn_x_dim_2: int = int(params["cnn_x_dim_2"])
    cnn_y_dim_2: int = int(params["cnn_y_dim_2"])
    out_channels_1: int = int(params["out_channels_1"])
    out_channels_2: int = int(params["out_channels_2"])

    encoder_x_dim: int = int(params["encoder_x_dim"])
    encoder_y_dim: int = int(params["encoder_y_dim"])

    # RRAM address width: ceil(log2(reram_size))
    rram_row_addr_width: int = math.ceil(math.log2(reram_size))

    # Encoder PE count
    enc_inputs_num: int = encoder_x_dim * encoder_y_dim

    # Hypervector segment width: hd_dim / (encoder_x_dim * encoder_y_dim)
    # Integer division — must divide evenly for valid RTL
    if hd_dim % enc_inputs_num != 0:
        raise ValueError(
            f"hd_dim ({hd_dim}) must be divisible by encoder_x_dim*encoder_y_dim "
            f"({enc_inputs_num}). Got remainder {hd_dim % enc_inputs_num}."
        )
    hv_seg_width: int = hd_dim // enc_inputs_num

    macros: dict[str, int | str] = {
        # Hypervector geometry
        "HV_LENGTH": hd_dim,
        "INNER_DIM": inner_dim,
        "HV_SEG_WIDTH": hv_seg_width,

        # RRAM
        "RRAM_ROW_ADDR_WIDTH": rram_row_addr_width,

        # CNN Layer 1 spatial mapping
        "CNN1_INPUTS_NUM": cnn_x_dim_1 * cnn_y_dim_1,
        "CNN1_OUTPUTS_NUM": out_channels_1,

        # CNN Layer 2 spatial mapping
        "CNN2_INPUTS_NUM": cnn_x_dim_2 * cnn_y_dim_2,
        "CNN2_OUTPUTS_NUM": out_channels_2,

        # Encoder spatial mapping
        "ENC_INPUTS_NUM": enc_inputs_num,
    }
    return macros


def _write_svh(macros: dict[str, int | str], output_path: Path) -> None:
    """Write the macro dictionary to a SystemVerilog header (.svh) file."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by json_to_svh.py — DO NOT EDIT MANUALLY",
        "// Generated at runtime by the DSE framework.",
        "`ifndef CONFIG_MACROS_SVH",
        "`define CONFIG_MACROS_SVH",
        "",
    ]
    for name, value in macros.items():
        lines.append(f"`define {name} {value}")
    lines += ["", "`endif // CONFIG_MACROS_SVH", ""]
    output_path.write_text("\n".join(lines), encoding="utf-8")


def _patch_tcl_clock(frequency_hz: float, template_path: Path, output_path: Path) -> None:
    """
    Patch the DC synthesis TCL script to set the correct clock period.

    The template TCL file must contain a placeholder line of the form:
        create_clock -period CLOCK_PERIOD_PLACEHOLDER [get_ports clk]

    This function replaces CLOCK_PERIOD_PLACEHOLDER with the computed period in ns.
    """
    period_ns: float = round(1e9 / frequency_hz, 4)

    if not template_path.exists():
        raise FileNotFoundError(
            f"TCL template not found: {template_path}\n"
            "Create 'hardware/dc/synth_template.tcl' with placeholder "
            "'CLOCK_PERIOD_PLACEHOLDER' in the create_clock command."
        )

    tcl_content = template_path.read_text(encoding="utf-8")
    if "CLOCK_PERIOD_PLACEHOLDER" not in tcl_content:
        raise ValueError(
            "TCL template does not contain 'CLOCK_PERIOD_PLACEHOLDER'. "
            "Cannot inject clock period dynamically."
        )

    patched = tcl_content.replace("CLOCK_PERIOD_PLACEHOLDER", str(period_ns))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(patched, encoding="utf-8")


# ── Entry Point ───────────────────────────────────────────────────────────────

def translate(params: dict) -> None:
    """Main translation function: params dict → SVH file + patched TCL."""
    macros = _derive_macros(params)
    _write_svh(macros, SVH_OUTPUT)

    frequency_hz: float = float(params.get("frequency", 1e8))
    _patch_tcl_clock(frequency_hz, TCL_TEMPLATE, TCL_OUTPUT)

    print(
        f"[json_to_svh] Written {SVH_OUTPUT.name} "
        f"({len(macros)} macros, clock={1e9/frequency_hz:.3f} ns)"
    )


def main() -> None:
    raw = sys.stdin.read().strip()
    if not raw:
        print("ERROR: No JSON input on stdin.", file=sys.stderr)
        sys.exit(1)
    try:
        params = json.loads(raw)
    except json.JSONDecodeError as exc:
        print(f"ERROR: Invalid JSON: {exc}", file=sys.stderr)
        sys.exit(1)

    try:
        translate(params)
    except (ValueError, FileNotFoundError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
