// =============================================================================
// tb_top.sv — Parameterized Gate-Level Simulation Testbench
//
// Deployment target: ~/workspace/fsl-hd/tb/tb_top.sv
//   (copy this file to fsl-hd/tb/ before running `make sim`)
//
// Include files (paths relative to fsl-hd/tb/ where this file lives):
//   config_macros.svh : Hardware geometry (generated by json_to_svh.py → ../verilog/include/)
//   tb_macros.svh     : Test environment constants (generated by json_to_svh.py → tb/)
//
// Test Data (loaded via $readmemh — paths relative to fsl-hd/ where simv runs):
//   tb/data/inputs.hex   : Input feature vectors, one per line, hex-encoded
//   tb/data/labels.hex   : Golden label per input vector
//   tb/data/weights.hex  : HDnn class hypervectors (for RRAM initialisation)
//
// Outputs written to fsl-hd/reports/:
//   vcs_simulation.log  : Contains "Total cycles: N" and "HW Accuracy: A / B"
//   (activity.saif written by $toggle_report for PrimeTime PX)
//
// IMPORTANT: Replace 'hdnn_top' with the actual synthesized top module name.
// =============================================================================

`timescale 1ns / 1ps

// Include paths relative to THIS file's location: fsl-hd/tb/
`include "../verilog/include/config_macros.svh"
`include "tb_macros.svh"

module tb_top;

// ── Clock & Reset ─────────────────────────────────────────────────────────────
reg clk;
reg rst_n;

// Generate clock with half-period from tb_macros.svh (unit: ns)
initial clk = 0;
always #(`TB_CLK_PERIOD_NS / 2.0) clk = ~clk;

// ── DUT Port Signals ──────────────────────────────────────────────────────────
// TODO: Adapt port declarations to match fsl-hd/verilog/hdl/ top-level interface.
//       Macro widths are driven by config_macros.svh (written by json_to_svh.py).

reg  [`HV_LENGTH-1:0]      dut_hv_in;       // Input hypervector
reg  [`ENC_INPUTS_NUM-1:0] dut_feature_in;  // Encoded feature input
reg                         dut_valid_in;    // Input valid strobe
wire [`HV_LENGTH-1:0]      dut_hv_out;      // Output (class match) hypervector
wire                         dut_valid_out;  // Output valid strobe
wire [7:0]                   dut_pred_class; // Predicted class label (8-bit)

// ── DUT Instantiation ─────────────────────────────────────────────────────────
// TODO: Replace 'hdnn_top' and adapt port connections to the actual module.
hdnn_top u_dut (
    .clk        (clk),
    .rst_n      (rst_n),
    .feature_in (dut_feature_in),
    .valid_in   (dut_valid_in),
    .pred_class (dut_pred_class),
    .valid_out  (dut_valid_out)
);

// ── Test Vector Memory ────────────────────────────────────────────────────────
reg [7:0] input_mem  [`TB_NUM_VECTORS-1:0][`ENC_INPUTS_NUM-1:0];
reg [7:0] label_mem  [`TB_NUM_VECTORS-1:0];
reg [7:0] weight_mem [`HV_LENGTH-1:0][`HV_LENGTH-1:0];

// ── Cycle Counter & Accuracy ──────────────────────────────────────────────────
integer cycle_count;
integer correct_count;
integer i;

// ── SAIF Activity Dump Setup ──────────────────────────────────────────────────
// PrimeTime PX reads this file to compute exact dynamic power.
initial begin
    $set_gate_level_monitoring("rtl_on");
    $set_toggle_region(u_dut);
    $toggle_start();
end

// ── Main Test Sequence ────────────────────────────────────────────────────────
initial begin
    // Load test data from hex files; paths relative to CWD = fsl-hd/ (where simv runs)
    $readmemh(`TB_INPUT_FILE,  input_mem);
    $readmemh(`TB_GOLDEN_FILE, label_mem);
    $readmemh(`TB_WEIGHT_FILE, weight_mem);

    cycle_count   = 0;
    correct_count = 0;

    // Reset DUT
    rst_n        = 0;
    dut_valid_in = 0;
    dut_feature_in = 0;
    repeat(4) @(posedge clk);
    rst_n = 1;
    @(posedge clk);

    // Drive each test vector through the DUT
    for (i = 0; i < `TB_NUM_VECTORS; i = i + 1) begin
        dut_feature_in = input_mem[i];
        dut_valid_in   = 1;
        @(posedge clk);
        cycle_count = cycle_count + 1;

        dut_valid_in = 0;
        while (!dut_valid_out) begin
            @(posedge clk);
            cycle_count = cycle_count + 1;
        end

        if (dut_pred_class == label_mem[i])
            correct_count = correct_count + 1;

        @(posedge clk);
        cycle_count = cycle_count + 1;
    end

    // ── Stop Activity Monitoring & Dump SAIF ──────────────────────────────
    $toggle_stop();
    // Output path relative to CWD = fsl-hd/ where simv runs
    $toggle_report("reports/activity.saif", 1.0e-9, "tb_top");

    // ── Print Results (parsed by parsers/parse_vcs.py) ────────────────────
    $display("Total cycles: %0d", cycle_count);
    $display("HW Accuracy: %0d / %0d", correct_count, `TB_NUM_VECTORS);

    $finish;
end

// ── Watchdog Timer ────────────────────────────────────────────────────────────
initial begin
    #(10_000_000 * `TB_CLK_PERIOD_NS);
    $display("[WATCHDOG] Simulation exceeded time limit. Aborting.");
    $finish;
end

endmodule
