// AUTO-GENERATED by json_to_svh.py — DO NOT EDIT MANUALLY
// Generated at runtime by the DSE framework.
`ifndef CONFIG_MACROS_SVH
`define CONFIG_MACROS_SVH

`define HV_LENGTH 2048
`define INNER_DIM 1024
`define HV_SEG_WIDTH 32
`define RRAM_ROW_ADDR_WIDTH 8
`define CNN1_INPUTS_NUM 256
`define CNN1_OUTPUTS_NUM 4
`define CNN2_INPUTS_NUM 16
`define CNN2_OUTPUTS_NUM 8
`define ENC_INPUTS_NUM 64
`define WEIGHT_MEM_ADDR_WIDTH 5

`endif // CONFIG_MACROS_SVH
